import { UserProvider } from "@auth0/nextjs-auth0/client";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Righthome AI",
  description: "Generated by create next app",
};

// Auth0 configuration
const auth0Domain = "dev-oqeu2nb3dvlee8hw.us.auth0.com";
const auth0ClientId = "nI71iKpYQY4KKqRSyd6fz6Lv37zhfT2g";
const auth0RedirectUri = "http://localhost:3000/callback";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <UserProvider>
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          {children}
        </body>
      </UserProvider>
    </html>
  );
}
